name: PaperPreLogin
version: '${project.version}'
main: cn.paper_card.paper_pre_login.PluginMain
api-version: '1.20'
folia-supported: true
author: Paper99

softdepend:
  - PaperWhitelist
  - PaperCardAuth
  - DisallowAll
  - LittleSkinLogin
  - PaperLogin
